### ISSUE TITLE
On Long press trigger

### ISSUE THREAD

**Issue by planasmultimedia** [MohamedRejeb/compose-dnd#2]
Nice project man ! Its so useful, i was wondering if you could include a LongPress trigger so its more usable, also i'm having troubles to scroll, it detects the drag state.

Thank you for your contribution !

**Comment by MohamedRejeb** [comment]
Thanks!
I'll try to provide clear documentation ASAP. The long press is supported, you can try this:
```kotlin
rememberReorderState<LayerNode>(
    dragAfterLongPress = true
)
```

**Comment by planasmultimedia** [comment]
Cool ! Thank you very much for your quick response <3. I was also trying to enable/disable the behaviour, using an "Edit" button to enable the drag and drop feature. Is better to change between the Draggable list and a simple lazy column to enable/disable or there is any other feature?

**Comment by MohamedRejeb** [comment]
I'm considering adding this feature in the next release. It should be available this week with the update to compose 1.6.0.

The current implementation of the scroll down while dragging is not the best. That's why I added it only in the sample, not in the library itself. I'll try to improve it more.

**Comment by MohamedRejeb** [comment]
I'll close this issue since the long click is supported, can you open a new one issue for the enable/disable drag feature?

**Comment by planasmultimedia** [comment]
Thank man ! Looking forward to it
